// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA10vSduReQ5zzUbtdNRyQkH7QlZnedpPU',
    appId: '1:323889989200:web:abd7c87d656be369e53355',
    messagingSenderId: '323889989200',
    projectId: 'say-v-18b2d',
    authDomain: 'say-v-18b2d.firebaseapp.com',
    storageBucket: 'say-v-18b2d.firebasestorage.app',
    measurementId: 'G-81W00RFS7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOI7lM4gmxPSBmEVxPT9FpIav6A8EWveY',
    appId: '1:323889989200:android:a18412658ab0e70fe53355',
    messagingSenderId: '323889989200',
    projectId: 'say-v-18b2d',
    storageBucket: 'say-v-18b2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKovfc_lOMbbN59tF1fLsCc22OyGda7jU',
    appId: '1:323889989200:ios:7d5a1ea1de8c816ae53355',
    messagingSenderId: '323889989200',
    projectId: 'say-v-18b2d',
    storageBucket: 'say-v-18b2d.firebasestorage.app',
    iosBundleId: 'com.example.sayv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKovfc_lOMbbN59tF1fLsCc22OyGda7jU',
    appId: '1:323889989200:ios:7d5a1ea1de8c816ae53355',
    messagingSenderId: '323889989200',
    projectId: 'say-v-18b2d',
    storageBucket: 'say-v-18b2d.firebasestorage.app',
    iosBundleId: 'com.example.sayv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA10vSduReQ5zzUbtdNRyQkH7QlZnedpPU',
    appId: '1:323889989200:web:3313d1d06e9766f4e53355',
    messagingSenderId: '323889989200',
    projectId: 'say-v-18b2d',
    authDomain: 'say-v-18b2d.firebaseapp.com',
    storageBucket: 'say-v-18b2d.firebasestorage.app',
    measurementId: 'G-DEHG96E36M',
  );

}