"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.storesData = void 0;
exports.storesData = {
    "stores": [
        {
            "storeId": "12345678",
            "name": "The Maple Tavern",
            "category": ["happy_hour", "special_events"],
            "cuisineTypes": ["American", "Canadian", "Bar", "Late Night"],
            "contactNumber": "6045551234",
            "location": {
                "latitude": 49.2827,
                "longitude": -123.1207,
            },
            "ratings": [4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0],
            "totalRatings": 487,
            "menus": [
                {
                    "itemId": "87654321",
                    "name": "Draft Beer",
                    "price": 5.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "87654322",
                    "name": "Wings",
                    "price": 8.99,
                    "type": "food",
                },
                {
                    "itemId": "87654323",
                    "name": "House Wine",
                    "price": 6.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "87654324",
                    "name": "Nachos",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "87654325",
                    "name": "Soft Drinks",
                    "price": 2.99,
                    "type": "drink",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 0,
                    "closeHour": 2,
                    "closeMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 15,
                    "startMinute": 0,
                    "endHour": 18,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "startHour": 22,
                    "startMinute": 0,
                    "endHour": 1,
                    "endMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["FRI", "SAT"],
                },
            ],
            "is24Hours": false,
        },
        {
            "storeId": "23456789",
            "name": "Sushi Paradise",
            "category": ["all_you_can_eat"],
            "cuisineTypes": ["Japanese", "Asian", "Seafood", "Group Dining"],
            "contactNumber": "7781125070",
            "location": {
                "latitude": 49.2634,
                "longitude": -123.1548,
            },
            "ratings": [4.0, 4.5, 4.0, 3.5, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0],
            "totalRatings": 156,
            "menus": [
                {
                    "itemId": "98765431",
                    "name": "Salmon Nigiri",
                    "price": 3.99,
                    "type": "food",
                },
                {
                    "itemId": "98765432",
                    "name": "California Roll",
                    "price": 4.99,
                    "type": "food",
                },
                {
                    "itemId": "98765433",
                    "name": "Green Tea",
                    "price": 2.50,
                    "type": "drink",
                },
                {
                    "itemId": "98765434",
                    "name": "Sake",
                    "price": 7.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "98765435",
                    "name": "Miso Soup",
                    "price": 2.99,
                    "type": "food",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 30,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [],
            "is24Hours": false,
        },
        {
            "storeId": "34567890",
            "name": "Korean BBQ House",
            "category": ["all_you_can_eat", "special_events"],
            "cuisineTypes": ["Korean", "Asian", "BBQ", "Group Dining", "Late Night"],
            "contactNumber": "6040477008",
            "location": {
                "latitude": 49.2651,
                "longitude": -123.1007,
            },
            "ratings": [4.5, 5.0, 4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0],
            "totalRatings": 892,
            "menus": [
                {
                    "itemId": "76543210",
                    "name": "Pork Belly",
                    "price": 15.99,
                    "type": "food",
                },
                {
                    "itemId": "76543211",
                    "name": "Soju",
                    "price": 13.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "76543212",
                    "name": "Beef Short Ribs",
                    "price": 18.99,
                    "type": "food",
                },
                {
                    "itemId": "76543213",
                    "name": "Korean Beer",
                    "price": 5.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "76543214",
                    "name": "Kimchi Stew",
                    "price": 12.99,
                    "type": "food",
                },
            ],
            "is24Hours": true,
            "happyHours": [],
            "businessHours": [],
        },
        {
            "storeId": "45678901",
            "name": "Taco Tuesday",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["Mexican", "Latin", "Bar"],
            "contactNumber": "7786211270",
            "location": {
                "latitude": 49.2726,
                "longitude": -123.0696,
            },
            "ratings": [4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0],
            "totalRatings": 234,
            "menus": [
                {
                    "itemId": "45678902",
                    "name": "Beef Tacos",
                    "price": 10.99,
                    "type": "food",
                },
                {
                    "itemId": "45678903",
                    "name": "Chicken Quesadilla",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "45678904",
                    "name": "Guacamole & Chips",
                    "price": 7.99,
                    "type": "food",
                },
                {
                    "itemId": "45678905",
                    "name": "Margarita",
                    "price": 6.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "45678906",
                    "name": "Mexican Beer",
                    "price": 5.99,
                    "type": "alcohol",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 15,
                    "startMinute": 0,
                    "endHour": 18,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["TUE"],
                },
            ],
            "is24Hours": false,
        },
        {
            "storeId": "56789012",
            "name": "Pub & Grub",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["British", "American", "Bar", "Pub Food"],
            "contactNumber": "6044324522",
            "location": {
                "latitude": 49.2687,
                "longitude": -123.1557,
            },
            "ratings": [4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0],
            "totalRatings": 756,
            "menus": [
                {
                    "itemId": "56789013",
                    "name": "Fish & Chips",
                    "price": 14.99,
                    "type": "food",
                },
                {
                    "itemId": "56789014",
                    "name": "Bangers & Mash",
                    "price": 13.99,
                    "type": "food",
                },
                {
                    "itemId": "56789015",
                    "name": "Beef Wellington",
                    "price": 18.99,
                    "type": "food",
                },
                {
                    "itemId": "56789016",
                    "name": "Pint of Ale",
                    "price": 5.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "56789017",
                    "name": "Whiskey Sour",
                    "price": 7.99,
                    "type": "alcohol",
                },
            ],
            "businessHours": [
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 11,
                    "openMinute": 0,
                    "closeHour": 2,
                    "closeMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 16,
                    "startMinute": 0,
                    "endHour": 19,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
            ],
            "is24Hours": false,
        },
        {
            "storeId": "67890123",
            "name": "Sushi Express",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["Japanese", "Sushi", "Asian", "Late Night"],
            "contactNumber": "7788260448",
            "location": {
                "latitude": 49.2815,
                "longitude": -123.1190,
            },
            "ratings": [4.0, 4.5, 4.0, 3.5, 4.0, 4.5, 3.5, 4.0],
            "totalRatings": 8,
            "menus": [
                {
                    "itemId": "67890124",
                    "name": "California Roll",
                    "price": 8.99,
                    "type": "food",
                },
                {
                    "itemId": "67890125",
                    "name": "Tuna Sashimi",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "67890126",
                    "name": "Salmon Nigiri",
                    "price": 10.99,
                    "type": "food",
                },
                {
                    "itemId": "67890127",
                    "name": "Green Tea",
                    "price": 2.99,
                    "type": "drink",
                },
                {
                    "itemId": "67890128",
                    "name": "Sapporo Beer",
                    "price": 5.99,
                    "type": "alcohol",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 30,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 14,
                    "startMinute": 30,
                    "endHour": 17,
                    "endMinute": 30,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
            ],
            "is24Hours": false,
        },
        {
            "storeId": "78901234",
            "name": "Pizza Paradise",
            "category": ["deals_and_discounts", "special_events"],
            "cuisineTypes": ["Italian", "Pizza", "Family Style"],
            "contactNumber": "6042492547",
            "location": {
                "latitude": 49.2835,
                "longitude": -123.1160,
            },
            "ratings": [4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0],
            "totalRatings": 167,
            "menus": [
                {
                    "itemId": "32109876",
                    "name": "Margherita Pizza",
                    "price": 14.99,
                    "type": "food",
                },
                {
                    "itemId": "32109875",
                    "name": "Italian Wine",
                    "price": 8.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "32109874",
                    "name": "Garlic Bread",
                    "price": 5.99,
                    "type": "food",
                },
                {
                    "itemId": "32109873",
                    "name": "Caesar Salad",
                    "price": 9.99,
                    "type": "food",
                },
                {
                    "itemId": "32109872",
                    "name": "Tiramisu",
                    "price": 6.99,
                    "type": "food",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 1,
                    "closeMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["FRI", "SAT"],
                },
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SUN"],
                },
            ],
            "happyHours": [],
            "is24Hours": false,
        },
        {
            "storeId": "89012345",
            "name": "Vegan Delight",
            "category": ["deals_and_discounts", "special_events"],
            "cuisineTypes": ["Vegan", "Healthy", "International", "Gluten-Free", "Organic"],
            "contactNumber": "7784033721",
            "location": {
                "latitude": 49.2595,
                "longitude": -123.2390,
            },
            "ratings": [],
            "totalRatings": 0,
            "businessHours": [
                {
                    "openHour": 8,
                    "openMinute": 0,
                    "closeHour": 21,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 9,
                    "openMinute": 0,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [],
            "menus": [
                {
                    "itemId": "89012346",
                    "name": "Vegan Buddha Bowl",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "89012347",
                    "name": "Green Smoothie",
                    "price": 5.99,
                    "type": "drink",
                },
                {
                    "itemId": "89012348",
                    "name": "Quinoa Salad",
                    "price": 9.99,
                    "type": "food",
                },
                {
                    "itemId": "89012349",
                    "name": "Vegan Burger",
                    "price": 14.99,
                    "type": "food",
                },
                {
                    "itemId": "89012350",
                    "name": "Cold-Pressed Juice",
                    "price": 6.50,
                    "type": "drink",
                },
                {
                    "itemId": "89012351",
                    "name": "Chia Pudding",
                    "price": 7.99,
                    "type": "food",
                },
                {
                    "itemId": "89012352",
                    "name": "Herbal Tea",
                    "price": 3.99,
                    "type": "drink",
                },
            ],
            "is24Hours": false,
        },
        {
            "storeId": "90123456",
            "name": "Healthy Bites",
            "category": ["deals_and_discounts"],
            "cuisineTypes": ["Healthy", "American", "Cafe", "Breakfast", "Brunch"],
            "contactNumber": "6046767829",
            "location": {
                "latitude": 49.2845,
                "longitude": -123.1375,
            },
            "ratings": [4.5, 4.0, 3.5],
            "totalRatings": 3,
            "businessHours": [
                {
                    "openHour": 7,
                    "openMinute": 0,
                    "closeHour": 20,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [],
            "menus": [
                {
                    "itemId": "90123457",
                    "name": "Avocado Toast",
                    "price": 8.99,
                    "type": "food",
                },
                {
                    "itemId": "90123458",
                    "name": "Acai Bowl",
                    "price": 9.99,
                    "type": "food",
                },
                {
                    "itemId": "90123459",
                    "name": "Green Juice",
                    "price": 5.99,
                    "type": "drink",
                },
                {
                    "itemId": "90123460",
                    "name": "Oatmeal with Berries",
                    "price": 6.50,
                    "type": "food",
                },
                {
                    "itemId": "90123461",
                    "name": "Chia Pudding with Almonds",
                    "price": 7.99,
                    "type": "food",
                },
                {
                    "itemId": "90123462",
                    "name": "Cold Brew Coffee",
                    "price": 4.50,
                    "type": "drink",
                },
                {
                    "itemId": "90123463",
                    "name": "Smoothie Bowl",
                    "price": 10.99,
                    "type": "food",
                },
            ],
            "is24Hours": false,
        },
        {
            "storeId": "01234567",
            "name": "BBQ King",
            "category": ["happy_hour", "all_you_can_eat"],
            "cuisineTypes": ["BBQ", "American", "Southern", "Grill", "Smokehouse"],
            "contactNumber": "7786666515",
            "location": {
                "latitude": 49.2745,
                "longitude": -123.1230,
            },
            "ratings": [4.0, 4.5, 5.0, 4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0],
            "totalRatings": 678,
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 30,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["TUE", "WED", "THU", "FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 15,
                    "startMinute": 0,
                    "endHour": 18,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["TUE", "WED", "THU", "FRI"],
                },
            ],
            "is24Hours": false,
            "menus": [
                {
                    "itemId": "12345678",
                    "name": "BBQ Ribs",
                    "price": 18.99,
                    "type": "food",
                },
                {
                    "itemId": "12345679",
                    "name": "Pulled Pork Sandwich",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "12345680",
                    "name": "Grilled Chicken Wings",
                    "price": 10.99,
                    "type": "food",
                },
                {
                    "itemId": "12345681",
                    "name": "Smoked Brisket",
                    "price": 22.99,
                    "type": "food",
                },
                {
                    "itemId": "12345682",
                    "name": "BBQ Sauce",
                    "price": 2.50,
                    "type": "food",
                },
                {
                    "itemId": "12345683",
                    "name": "Craft Beer",
                    "price": 6.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "12345684",
                    "name": "Whiskey",
                    "price": 8.99,
                    "type": "alcohol",
                },
            ],
        },
        {
            "storeId": "11223344",
            "name": "Dim Sum Palace",
            "category": ["all_you_can_eat", "special_events"],
            "cuisineTypes": ["Chinese", "Asian", "Dim Sum"],
            "contactNumber": "6047450654",
            "location": {
                "latitude": 49.2798,
                "longitude": -123.1010,
            },
            "ratings": [4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0],
            "totalRatings": 345,
            "businessHours": [
                {
                    "openHour": 9,
                    "openMinute": 0,
                    "closeHour": 21,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "THU", "FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [],
            "is24Hours": false,
            "menus": [
                {
                    "itemId": "23456789",
                    "name": "Shrimp Dumplings",
                    "price": 7.99,
                    "type": "food",
                },
                {
                    "itemId": "23456790",
                    "name": "Pork Buns",
                    "price": 5.99,
                    "type": "food",
                },
                {
                    "itemId": "23456791",
                    "name": "Chicken Siu Mai",
                    "price": 6.99,
                    "type": "food",
                },
                {
                    "itemId": "23456792",
                    "name": "Beef Spring Rolls",
                    "price": 4.99,
                    "type": "food",
                },
                {
                    "itemId": "23456793",
                    "name": "Egg Custard Tarts",
                    "price": 3.99,
                    "type": "food",
                },
                {
                    "itemId": "23456794",
                    "name": "Chinese Tea",
                    "price": 2.50,
                    "type": "drink",
                },
                {
                    "itemId": "23456795",
                    "name": "Lychee Martini",
                    "price": 7.99,
                    "type": "alcohol",
                },
            ],
        },
        {
            "storeId": "22334455",
            "name": "Burger Joint",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["American", "Burgers", "Fast Food", "Bar"],
            "contactNumber": "7785791633",
            "location": {
                "latitude": 49.2530,
                "longitude": -123.1015,
            },
            "ratings": [2.0, 2.5, 3.0, 2.5, 2.0, 3.0, 2.5, 3.0, 2.5, 2.0, 3.5, 2.0, 2.5, 3.0, 2.5, 2.0, 2.5, 3.0, 2.5, 3.0],
            "totalRatings": 267,
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 15,
                    "startMinute": 0,
                    "endHour": 18,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
            ],
            "is24Hours": false,
            "menus": [
                {
                    "itemId": "34567890",
                    "name": "Classic Cheeseburger",
                    "price": 9.99,
                    "type": "food",
                },
                {
                    "itemId": "34567891",
                    "name": "BBQ Bacon Burger",
                    "price": 11.49,
                    "type": "food",
                },
                {
                    "itemId": "34567892",
                    "name": "Veggie Burger",
                    "price": 8.99,
                    "type": "food",
                },
                {
                    "itemId": "34567893",
                    "name": "Fries",
                    "price": 3.99,
                    "type": "food",
                },
                {
                    "itemId": "34567894",
                    "name": "Onion Rings",
                    "price": 4.99,
                    "type": "food",
                },
                {
                    "itemId": "34567895",
                    "name": "House IPA",
                    "price": 5.49,
                    "type": "alcohol",
                },
                {
                    "itemId": "34567896",
                    "name": "Soft Drink",
                    "price": 2.50,
                    "type": "drink",
                },
            ],
        },
        {
            "storeId": "33445566",
            "name": "Mediterranean Grill",
            "category": ["deals_and_discounts", "special_events"],
            "cuisineTypes": ["Mediterranean", "Greek", "Middle Eastern", "Healthy"],
            "contactNumber": "7785993715",
            "location": {
                "latitude": 49.2677,
                "longitude": -123.1685,
            },
            "ratings": [4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0],
            "totalRatings": 189,
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 30,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT"],
                },
            ],
            "happyHours": [],
            "is24Hours": false,
            "menus": [
                {
                    "itemId": "45678901",
                    "name": "Chicken Shawarma",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "45678902",
                    "name": "Falafel Plate",
                    "price": 10.99,
                    "type": "food",
                },
                {
                    "itemId": "45678903",
                    "name": "Greek Salad",
                    "price": 7.99,
                    "type": "food",
                },
                {
                    "itemId": "45678904",
                    "name": "Hummus with Pita",
                    "price": 5.99,
                    "type": "food",
                },
                {
                    "itemId": "45678905",
                    "name": "Lamb Kebab",
                    "price": 14.99,
                    "type": "food",
                },
                {
                    "itemId": "45678906",
                    "name": "Mint Lemonade",
                    "price": 3.50,
                    "type": "drink",
                },
                {
                    "itemId": "45678907",
                    "name": "Greek Yogurt Parfait",
                    "price": 4.99,
                    "type": "food",
                },
            ],
        },
        {
            "storeId": "44556677",
            "name": "Ice Cream Paradise",
            "category": ["deals_and_discounts", "special_events"],
            "cuisineTypes": ["Dessert", "Ice Cream", "Family Friendly"],
            "contactNumber": "6046284660",
            "location": {
                "latitude": 49.2715,
                "longitude": -123.1365,
            },
            "ratings": [3.0, 2.5, 3.0, 2.5, 3.5, 3.0, 2.5, 3.0, 3.5, 2.5, 3.0, 2.5, 3.0, 2.5, 3.5, 3.0, 2.5, 3.0, 3.5, 2.5],
            "totalRatings": 156,
            "businessHours": [
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT"],
                },
            ],
            "happyHours": [],
            "is24Hours": false,
            "menus": [
                {
                    "itemId": "56789012",
                    "name": "Vanilla Ice Cream",
                    "price": 4.99,
                    "type": "food",
                },
                {
                    "itemId": "56789013",
                    "name": "Chocolate Fudge Sundae",
                    "price": 6.99,
                    "type": "food",
                },
                {
                    "itemId": "56789014",
                    "name": "Strawberry Sorbet",
                    "price": 5.49,
                    "type": "food",
                },
                {
                    "itemId": "56789015",
                    "name": "Mint Chocolate Chip Cone",
                    "price": 3.99,
                    "type": "food",
                },
                {
                    "itemId": "56789016",
                    "name": "Banana Split",
                    "price": 7.49,
                    "type": "food",
                },
                {
                    "itemId": "56789017",
                    "name": "Root Beer Float",
                    "price": 4.49,
                    "type": "drink",
                },
                {
                    "itemId": "56789018",
                    "name": "Chocolate Chip Cookie Dough",
                    "price": 5.99,
                    "type": "food",
                },
            ],
        },
        {
            "storeId": "55667788",
            "name": "Pho House",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["Vietnamese", "Asian", "Soup", "Noodles"],
            "contactNumber": "6047817749",
            "location": {
                "latitude": 49.2482,
                "longitude": -123.0901,
            },
            "ratings": [4.0, 4.5, 5.0, 4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0],
            "totalRatings": 432,
            "businessHours": [
                {
                    "openHour": 10,
                    "openMinute": 0,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 14,
                    "startMinute": 30,
                    "endHour": 17,
                    "endMinute": 30,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
            ],
            "is24Hours": false,
            "menus": [
                {
                    "itemId": "67890123",
                    "name": "Pho Ga (Chicken Pho)",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "67890124",
                    "name": "Pho Bo (Beef Pho)",
                    "price": 13.49,
                    "type": "food",
                },
                {
                    "itemId": "67890125",
                    "name": "Banh Mi Sandwich",
                    "price": 6.99,
                    "type": "food",
                },
                {
                    "itemId": "67890126",
                    "name": "Spring Rolls (Goi Cuon)",
                    "price": 7.49,
                    "type": "food",
                },
                {
                    "itemId": "67890127",
                    "name": "Vietnamese Iced Coffee",
                    "price": 4.49,
                    "type": "drink",
                },
                {
                    "itemId": "67890128",
                    "name": "Bun Thit Nuong (Grilled Pork Vermicelli)",
                    "price": 10.99,
                    "type": "food",
                },
                {
                    "itemId": "67890129",
                    "name": "Coconut Water",
                    "price": 3.99,
                    "type": "drink",
                },
            ],
        },
        {
            "storeId": "55667715",
            "name": "BB.Q Chicken",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["Korean", "Chicken", "Asian", "Bar"],
            "contactNumber": "6049604370",
            "location": {
                "latitude": 49.2825,
                "longitude": -123.1195,
            },
            "ratings": [4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0],
            "totalRatings": 245,
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 30,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 15,
                    "startMinute": 0,
                    "endHour": 18,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
            ],
            "is24Hours": false,
            "menus": [
                {
                    "itemId": "78901234",
                    "name": "Korean Fried Chicken",
                    "price": 14.99,
                    "type": "food",
                },
                {
                    "itemId": "78901235",
                    "name": "Boneless Chicken Bites",
                    "price": 12.49,
                    "type": "food",
                },
                {
                    "itemId": "78901236",
                    "name": "Garlic Fries",
                    "price": 6.99,
                    "type": "food",
                },
                {
                    "itemId": "78901237",
                    "name": "Tteokbokki (Spicy Rice Cakes)",
                    "price": 7.49,
                    "type": "food",
                },
                {
                    "itemId": "78901238",
                    "name": "Soju (Korean Liquor)",
                    "price": 5.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "78901239",
                    "name": "Korean Beer (Cass)",
                    "price": 4.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "78901240",
                    "name": "Iced Green Tea",
                    "price": 3.49,
                    "type": "drink",
                },
            ],
        },
        {
            "storeId": "66778899",
            "name": "Langley Night Market",
            "category": ["special_events"],
            "cuisineTypes": ["Asian", "Street Food", "International", "Night Market"],
            "contactNumber": "7783943087",
            "location": {
                "latitude": 49.1042,
                "longitude": -122.6604,
            },
            "ratings": [],
            "totalRatings": 0,
            "businessHours": [
                {
                    "openHour": 17,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT"],
                },
            ],
            "happyHours": [],
            "is24Hours": false,
            "menus": [
                {
                    "itemId": "89101112",
                    "name": "Satay Skewers (Chicken or Beef)",
                    "price": 7.99,
                    "type": "food",
                },
                {
                    "itemId": "89101113",
                    "name": "Takoyaki (Octopus Balls)",
                    "price": 6.49,
                    "type": "food",
                },
                {
                    "itemId": "89101114",
                    "name": "Bubble Tea (Various Flavors)",
                    "price": 4.99,
                    "type": "drink",
                },
                {
                    "itemId": "89101115",
                    "name": "Fried Spring Rolls",
                    "price": 5.49,
                    "type": "food",
                },
                {
                    "itemId": "89101116",
                    "name": "Grilled Corn on the Cob",
                    "price": 3.99,
                    "type": "food",
                },
                {
                    "itemId": "89101117",
                    "name": "Dim Sum Platter",
                    "price": 8.99,
                    "type": "food",
                },
            ],
        },
        {
            "storeId": "77889900",
            "name": "Coquitlam Brew House",
            "category": ["happy_hour", "special_events"],
            "cuisineTypes": ["Pub Food", "Craft Beer", "American", "Bar", "Live Music"],
            "contactNumber": "6046264214",
            "location": {
                "latitude": 49.2838,
                "longitude": -122.7932,
            },
            "ratings": [4.0, 4.5, 5.0, 4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0],
            "totalRatings": 678,
            "businessHours": [
                {
                    "openHour": 16,
                    "openMinute": 0,
                    "closeHour": 2,
                    "closeMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["WED", "THU", "FRI", "SAT"],
                },
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 16,
                    "startMinute": 0,
                    "endHour": 19,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["WED", "THU", "FRI"],
                },
                {
                    "startHour": 22,
                    "startMinute": 0,
                    "endHour": 1,
                    "endMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["FRI", "SAT"],
                },
            ],
            "is24Hours": false,
            "menus": [
                {
                    "itemId": "12345678",
                    "name": "Classic Cheeseburger",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "12345679",
                    "name": "Fish and Chips",
                    "price": 14.99,
                    "type": "food",
                },
                {
                    "itemId": "12345680",
                    "name": "Buffalo Wings",
                    "price": 9.99,
                    "type": "food",
                },
                {
                    "itemId": "12345681",
                    "name": "Craft Beer (Variety of Types)",
                    "price": 5.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "12345682",
                    "name": "Pint of Lager",
                    "price": 4.49,
                    "type": "alcohol",
                },
                {
                    "itemId": "12345683",
                    "name": "Loaded Nachos",
                    "price": 8.99,
                    "type": "food",
                },
            ],
        },
        {
            "storeId": "88990011",
            "name": "White Rock Beach Bar",
            "category": ["happy_hour", "special_events"],
            "cuisineTypes": ["Seafood", "Bar", "American", "Grill", "Beach View"],
            "contactNumber": "6041822159",
            "location": {
                "latitude": 49.0253,
                "longitude": -122.8029,
            },
            "ratings": [4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0],
            "totalRatings": 345,
            "businessHours": [
                {
                    "openHour": 16,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU"],
                },
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 2,
                    "closeMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 16,
                    "startMinute": 0,
                    "endHour": 18,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU"],
                },
            ],
            "is24Hours": false,
            "menus": [
                {
                    "itemId": "12345684",
                    "name": "Grilled Salmon",
                    "price": 18.99,
                    "type": "food",
                },
                {
                    "itemId": "12345685",
                    "name": "Fish Tacos",
                    "price": 14.99,
                    "type": "food",
                },
                {
                    "itemId": "12345686",
                    "name": "Seafood Paella",
                    "price": 22.99,
                    "type": "food",
                },
                {
                    "itemId": "12345687",
                    "name": "Beachside Cocktail",
                    "price": 9.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "12345688",
                    "name": "Mojito",
                    "price": 7.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "12345689",
                    "name": "Grilled Veggie Skewers",
                    "price": 10.99,
                    "type": "food",
                },
            ],
        },
        {
            "storeId": "99001122",
            "name": "Maple Ridge Dawn Cafe",
            "category": ["deals_and_discounts"],
            "cuisineTypes": ["Breakfast", "Brunch", "Cafe", "Coffee"],
            "contactNumber": "6047626930",
            "location": {
                "latitude": 49.2193,
                "longitude": -122.5984,
            },
            "ratings": [2.0, 2.5, 3.0, 2.0, 2.5, 3.0, 2.5, 2.0],
            "totalRatings": 8,
            "businessHours": [
                {
                    "openHour": 6,
                    "openMinute": 0,
                    "closeHour": 15,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 7,
                    "openMinute": 0,
                    "closeHour": 16,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT"],
                },
            ],
            "happyHours": [],
            "is24Hours": false,
            "menus": [
                {
                    "itemId": "12345690",
                    "name": "Classic Breakfast Plate",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "12345691",
                    "name": "Avocado Toast",
                    "price": 8.99,
                    "type": "food",
                },
                {
                    "itemId": "12345692",
                    "name": "Pancake Stack",
                    "price": 10.99,
                    "type": "food",
                },
                {
                    "itemId": "12345693",
                    "name": "Cappuccino",
                    "price": 4.50,
                    "type": "drink",
                },
                {
                    "itemId": "12345694",
                    "name": "Latte",
                    "price": 4.99,
                    "type": "drink",
                },
                {
                    "itemId": "12345695",
                    "name": "Fresh Orange Juice",
                    "price": 3.50,
                    "type": "drink",
                },
            ],
        },
        {
            "storeId": "00112233",
            "name": "North Van Late Bar",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["Bar", "Pub Food", "Late Night"],
            "contactNumber": "7789510146",
            "location": {
                "latitude": 49.3114,
                "longitude": -123.0728,
            },
            "ratings": [4.0, 4.5, 5.0, 4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0],
            "totalRatings": 234,
            "businessHours": [
                {
                    "openHour": 16,
                    "openMinute": 0,
                    "closeHour": 1,
                    "closeMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["TUE", "WED", "THU"],
                },
                {
                    "openHour": 16,
                    "openMinute": 0,
                    "closeHour": 3,
                    "closeMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["FRI", "SAT"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 16,
                    "startMinute": 0,
                    "endHour": 19,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["TUE", "WED", "THU", "FRI"],
                },
                {
                    "startHour": 23,
                    "startMinute": 0,
                    "endHour": 2,
                    "endMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["FRI", "SAT"],
                },
            ],
            "is24Hours": false,
            "menus": [
                {
                    "itemId": "12345696",
                    "name": "Pub Burger",
                    "price": 10.99,
                    "type": "food",
                },
                {
                    "itemId": "12345697",
                    "name": "Loaded Nachos",
                    "price": 8.99,
                    "type": "food",
                },
                {
                    "itemId": "12345698",
                    "name": "Fried Chicken Wings",
                    "price": 7.99,
                    "type": "food",
                },
                {
                    "itemId": "12345699",
                    "name": "Beer on Tap",
                    "price": 5.50,
                    "type": "drink",
                },
                {
                    "itemId": "12345700",
                    "name": "Whiskey Shot",
                    "price": 4.99,
                    "type": "drink",
                },
                {
                    "itemId": "12345701",
                    "name": "Cocktail of the Day",
                    "price": 6.50,
                    "type": "drink",
                },
            ],
        },
        {
            "storeId": "11223344",
            "name": "Whistler Mountain Lodge",
            "category": ["happy_hour", "special_events"],
            "cuisineTypes": ["Fine Dining", "Canadian", "Steak", "Wine Bar", "Ski Resort"],
            "contactNumber": "7783593640",
            "location": {
                "latitude": 50.1162,
                "longitude": -122.9535,
            },
            "ratings": [4.5, 5.0, 4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0],
            "totalRatings": 567,
            "menus": [
                {
                    "itemId": "11223345",
                    "name": "Filet Mignon",
                    "price": 45.99,
                    "type": "food",
                },
                {
                    "itemId": "11223346",
                    "name": "Lobster Tail",
                    "price": 39.99,
                    "type": "food",
                },
                {
                    "itemId": "11223347",
                    "name": "Caesar Salad",
                    "price": 10.99,
                    "type": "food",
                },
                {
                    "itemId": "11223348",
                    "name": "Chardonnay",
                    "price": 12.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "11223349",
                    "name": "Cabernet Sauvignon",
                    "price": 14.99,
                    "type": "alcohol",
                },
            ],
            "businessHours": [
                {
                    "openHour": 7,
                    "openMinute": 0,
                    "closeHour": 11,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
                },
                {
                    "openHour": 17,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 17,
                    "startMinute": 0,
                    "endHour": 19,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
                },
            ],
            "is24Hours": false,
        },
        {
            "storeId": "22233344",
            "name": "Burnaby Sports Bar",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["Bar", "American", "Pub Food", "Sports Bar"],
            "contactNumber": "7788108334",
            "location": {
                "latitude": 49.2488,
                "longitude": -122.9805,
            },
            "ratings": [4.5, 4.0, 4.5, 5.0, 4.0, 4.5, 4.0, 4.5, 5.0, 4.0, 4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 4.5, 4.0, 4.5],
            "totalRatings": 342,
            "menus": [
                {
                    "itemId": "13221159",
                    "name": "Wings Platter",
                    "price": 15.99,
                    "type": "food",
                },
                {
                    "itemId": "49881593",
                    "name": "Draft Beer",
                    "price": 6.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "86579923",
                    "name": "Loaded Nachos",
                    "price": 18.99,
                    "type": "food",
                },
                {
                    "itemId": "90745524",
                    "name": "Sports Burger",
                    "price": 16.99,
                    "type": "food",
                },
                {
                    "itemId": "99078245",
                    "name": "House Cocktails",
                    "price": 8.99,
                    "type": "alcohol",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 30,
                    "closeHour": 1,
                    "closeMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU"],
                },
                {
                    "openHour": 11,
                    "openMinute": 30,
                    "closeHour": 2,
                    "closeMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 15,
                    "startMinute": 0,
                    "endHour": 18,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "startHour": 14,
                    "startMinute": 0,
                    "endHour": 17,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "is24Hours": false,
        },
        {
            "storeId": "33344455",
            "name": "Richmond Izakaya",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["Japanese", "Asian Fusion", "Izakaya", "Sushi"],
            "contactNumber": "7788070212",
            "location": {
                "latitude": 49.1666,
                "longitude": -123.1336,
            },
            "ratings": [4.0, 4.5, 5.0, 4.5, 4.0, 4.5, 5.0, 4.5, 4.0, 4.5, 5.0, 4.0],
            "totalRatings": 12,
            "menus": [
                {
                    "itemId": "00754362",
                    "name": "Sake Flight",
                    "price": 16.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "54958753",
                    "name": "Karaage",
                    "price": 9.99,
                    "type": "food",
                },
                {
                    "itemId": "98651234",
                    "name": "Sashimi Platter",
                    "price": 24.99,
                    "type": "food",
                },
                {
                    "itemId": "97529572",
                    "name": "Shochu Cocktails",
                    "price": 7.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "53275435",
                    "name": "Takoyaki",
                    "price": 8.99,
                    "type": "food",
                },
            ],
            "businessHours": [
                {
                    "openHour": 16,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 30,
                    "isNextDay": false,
                    "daysOfWeek": ["TUE", "WED", "THU"],
                },
                {
                    "openHour": 16,
                    "openMinute": 0,
                    "closeHour": 1,
                    "closeMinute": 0,
                    "isNextDay": true,
                    "daysOfWeek": ["FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 16,
                    "startMinute": 30,
                    "endHour": 18,
                    "endMinute": 30,
                    "isNextDay": false,
                    "daysOfWeek": ["TUE", "WED", "THU", "FRI"],
                },
                {
                    "startHour": 20,
                    "startMinute": 0,
                    "endHour": 1,
                    "endMinute": 30,
                    "isNextDay": true,
                    "daysOfWeek": ["FRI", "SAT"],
                },
            ],
            "is24Hours": false,
        },
        {
            "storeId": "44455566",
            "name": "Burnaby Late Night Pub",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["Pub Food", "Western", "Bar", "Late Night"],
            "contactNumber": "7788070212",
            "location": {
                "latitude": 49.2337,
                "longitude": -122.9977,
            },
            "ratings": [4.0, 4.5, 4.0, 4.5, 5.0, 4.0, 4.5, 4.0, 3.5, 4.0, 4.5, 5.0, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 4.5],
            "totalRatings": 289,
            "menus": [
                {
                    "itemId": "57908524",
                    "name": "Late Night Wings",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "22305684",
                    "name": "Craft Beer Flight",
                    "price": 14.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "89752996",
                    "name": "Loaded Potato Skins",
                    "price": 10.99,
                    "type": "food",
                },
                {
                    "itemId": "55492075",
                    "name": "House Signature Cocktails",
                    "price": 9.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "22076354",
                    "name": "Midnight Burger",
                    "price": 16.99,
                    "type": "food",
                },
            ],
            "businessHours": [
                {
                    "openHour": 16,
                    "openMinute": 0,
                    "closeHour": 1,
                    "closeMinute": 30,
                    "isNextDay": true,
                    "daysOfWeek": ["TUE", "WED", "THU"],
                },
                {
                    "openHour": 16,
                    "openMinute": 0,
                    "closeHour": 2,
                    "closeMinute": 30,
                    "isNextDay": true,
                    "daysOfWeek": ["FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 16,
                    "startMinute": 30,
                    "endHour": 18,
                    "endMinute": 30,
                    "isNextDay": false,
                    "daysOfWeek": ["TUE", "WED", "THU", "FRI"],
                },
                {
                    "startHour": 20,
                    "startMinute": 0,
                    "endHour": 1,
                    "endMinute": 30,
                    "isNextDay": true,
                    "daysOfWeek": ["FRI", "SAT"],
                },
            ],
            "is24Hours": false,
        },
        {
            "storeId": "12345678",
            "name": "Vancouver coast Grill",
            "category": ["deals_and_discounts", "happy_hour"],
            "cuisineTypes": ["Grill", "Seafood", "Western", "Barbecue"],
            "contactNumber": "7786528782",
            "location": {
                "latitude": 49.2827,
                "longitude": -123.1216,
            },
            "ratings": [4.0, 4.5, 5.0, 4.5, 3.5, 4.0, 4.5, 4.0, 3.5, 5.0, 4.5, 4.0, 5.0, 4.5, 4.0, 3.5, 4.5, 5.0, 4.0, 4.5],
            "totalRatings": 29,
            "menus": [
                {
                    "itemId": "10000001",
                    "name": "Grilled Salmon",
                    "price": 22.99,
                    "type": "food",
                },
                {
                    "itemId": "10000002",
                    "name": "BBQ Ribs",
                    "price": 26.99,
                    "type": "food",
                },
                {
                    "itemId": "10000003",
                    "name": "Seafood Paella",
                    "price": 30.99,
                    "type": "food",
                },
                {
                    "itemId": "10000004",
                    "name": "Craft Beer",
                    "price": 8.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "10000005",
                    "name": "House Red Wine",
                    "price": 12.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "10000006",
                    "name": "Crispy Fries",
                    "price": 6.99,
                    "type": "food",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 16,
                    "startMinute": 0,
                    "endHour": 18,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU"],
                },
                {
                    "startHour": 20,
                    "startMinute": 0,
                    "endHour": 22,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["FRI", "SAT"],
                },
            ],
            "is24Hours": false,
        }, {
            "storeId": "55667788",
            "name": "Burnaby Craft Brewery",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["Brewery", "Pub Food", "Craft Beer", "Bar"],
            "contactNumber": "7787423155",
            "location": {
                "latitude": 49.2622,
                "longitude": -122.9939,
            },
            "ratings": [4.5, 4.0, 5.0, 4.5, 3.5, 4.0, 4.5, 4.0, 5.0, 4.5, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 4.5, 3.5, 4.0],
            "totalRatings": 271,
            "menus": [
                {
                    "itemId": "55667701",
                    "name": "IPA Beer",
                    "price": 7.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "55667702",
                    "name": "Brewery Burger",
                    "price": 14.99,
                    "type": "food",
                },
                {
                    "itemId": "55667703",
                    "name": "Fried Calamari",
                    "price": 10.99,
                    "type": "food",
                },
                {
                    "itemId": "55667704",
                    "name": "Beer Sampler",
                    "price": 12.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "55667705",
                    "name": "Loaded Fries",
                    "price": 8.99,
                    "type": "food",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 16,
                    "startMinute": 0,
                    "endHour": 19,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "startHour": 20,
                    "startMinute": 0,
                    "endHour": 22,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["FRI"],
                },
            ],
            "is24Hours": false,
        },
        {
            "storeId": "66778899",
            "name": "West End Diner",
            "category": ["all_you_can_eat", "special_events"],
            "cuisineTypes": ["American", "Diner", "Breakfast", "Comfort Food"],
            "contactNumber": "6045581619",
            "location": {
                "latitude": 49.2820,
                "longitude": -123.1171,
            },
            "ratings": [4.0, 4.5, 5.0, 4.0, 3.5, 4.0, 4.5, 4.0, 5.0, 4.5, 4.0, 4.5, 3.5, 4.0, 4.5, 5.0, 4.0, 4.5, 3.5, 4.0],
            "totalRatings": 120,
            "menus": [
                {
                    "itemId": "66778801",
                    "name": "Classic Pancakes",
                    "price": 9.99,
                    "type": "food",
                },
                {
                    "itemId": "66778802",
                    "name": "Bacon & Eggs",
                    "price": 11.99,
                    "type": "food",
                },
                {
                    "itemId": "66778803",
                    "name": "Breakfast Burrito",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "66778804",
                    "name": "Bottomless Coffee",
                    "price": 3.99,
                    "type": "drink",
                },
                {
                    "itemId": "66778805",
                    "name": "Omelette of the Day",
                    "price": 13.99,
                    "type": "food",
                },
            ],
            "businessHours": [
                {
                    "openHour": 7,
                    "openMinute": 0,
                    "closeHour": 15,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 8,
                    "openMinute": 0,
                    "closeHour": 14,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [],
            "is24Hours": false,
        }, {
            "storeId": "77889900",
            "name": "Sunset Grill & Bar",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["American", "Grill", "BBQ", "Bar Food"],
            "contactNumber": "6043577926",
            "location": {
                "latitude": 49.2828,
                "longitude": -123.1207,
            },
            "ratings": [4.5, 5.0, 4.0, 4.5, 4.0, 5.0, 3.5, 4.0, 4.5, 4.0, 5.0, 4.5, 3.5, 4.5, 4.0, 5.0, 4.5, 4.0, 3.5, 5.0],
            "totalRatings": 965,
            "menus": [
                {
                    "itemId": "77889901",
                    "name": "BBQ Ribs",
                    "price": 18.99,
                    "type": "food",
                },
                {
                    "itemId": "77889902",
                    "name": "Grilled Chicken Wings",
                    "price": 13.99,
                    "type": "food",
                },
                {
                    "itemId": "77889903",
                    "name": "Buffalo Shrimp",
                    "price": 14.99,
                    "type": "food",
                },
                {
                    "itemId": "77889904",
                    "name": "Craft Beer Flight",
                    "price": 7.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "77889905",
                    "name": "Margarita",
                    "price": 9.99,
                    "type": "alcohol",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 10,
                    "openMinute": 0,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 16,
                    "startMinute": 0,
                    "endHour": 18,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "startHour": 14,
                    "startMinute": 0,
                    "endHour": 17,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "is24Hours": false,
        }, {
            "storeId": "98765432",
            "name": "Vancouver beer Bar",
            "category": ["happy_hour", "deals_and_discounts"],
            "cuisineTypes": ["Grill", "American", "Bar"],
            "contactNumber": "7784442587",
            "location": {
                "latitude": 49.2827,
                "longitude": -123.1207,
            },
            "ratings": [3.0, 3.5, 4.0, 4.0, 3.5, 4.5, 4.0, 3.5, 3.0, 4.5, 4.0, 4.0, 3.5, 4.5, 4.0, 3.5, 4.0, 3.5, 4.5, 4.0],
            "totalRatings": 480,
            "menus": [
                {
                    "itemId": "98765401",
                    "name": "Grilled Ribeye",
                    "price": 22.99,
                    "type": "food",
                },
                {
                    "itemId": "98765402",
                    "name": "Buffalo Wings",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "98765403",
                    "name": "House Margarita",
                    "price": 8.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "98765404",
                    "name": "BBQ Ribs",
                    "price": 19.99,
                    "type": "food",
                },
                {
                    "itemId": "98765405",
                    "name": "Craft Beer Selection",
                    "price": 7.99,
                    "type": "alcohol",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 0,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 16,
                    "startMinute": 0,
                    "endHour": 19,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
            ],
            "is24Hours": false,
        }, {
            "storeId": "87654321",
            "name": "West End Sushi & Bar",
            "category": ["happy_hour", "all_you_can_eat"],
            "cuisineTypes": ["Sushi", "Japanese", "Bar"],
            "contactNumber": "6047438201",
            "location": {
                "latitude": 49.2892,
                "longitude": -123.1304,
            },
            "ratings": [4.0, 4.5, 4.0, 5.0, 4.5, 4.0, 3.5, 5.0, 4.5, 4.0, 4.5, 3.5, 4.0, 5.0, 4.0, 4.5, 3.5, 4.0, 4.5, 4.0],
            "totalRatings": 389,
            "menus": [
                {
                    "itemId": "87654301",
                    "name": "Sushi Platter",
                    "price": 18.99,
                    "type": "food",
                },
                {
                    "itemId": "87654302",
                    "name": "Tuna Sashimi",
                    "price": 14.99,
                    "type": "food",
                },
                {
                    "itemId": "87654303",
                    "name": "Salmon Roll",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "87654304",
                    "name": "Japanese Beer",
                    "price": 5.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "87654305",
                    "name": "Mango Mojito",
                    "price": 7.99,
                    "type": "alcohol",
                },
            ],
            "businessHours": [
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 30,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 15,
                    "startMinute": 30,
                    "endHour": 18,
                    "endMinute": 30,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
            ],
            "is24Hours": false,
        }, {
            "storeId": "13579246",
            "name": "East Vancouver Meat Lovers",
            "category": ["special_events", "deals_and_discounts"],
            "cuisineTypes": ["BBQ", "Grill", "American", "Steakhouse"],
            "contactNumber": "6046629763",
            "location": {
                "latitude": 49.2606,
                "longitude": -123.1043,
            },
            "ratings": [1.0, 2.0, 4.0, 3.5, 4.5, 3.0, 4.0, 5.0, 4.5, 4.0, 3.5, 2.5, 4.5, 4.0, 5.0, 3.5, 4.0, 4.5, 5.0, 4.0],
            "totalRatings": 552,
            "menus": [
                {
                    "itemId": "13579201",
                    "name": "BBQ Ribs",
                    "price": 22.99,
                    "type": "food",
                },
                {
                    "itemId": "13579202",
                    "name": "Steak and Fries",
                    "price": 18.99,
                    "type": "food",
                },
                {
                    "itemId": "13579203",
                    "name": "Grilled Veggies",
                    "price": 8.99,
                    "type": "food",
                },
                {
                    "itemId": "13579204",
                    "name": "Craft Beer",
                    "price": 6.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "13579205",
                    "name": "Whiskey Sour",
                    "price": 7.99,
                    "type": "alcohol",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 30,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU"],
                },
                {
                    "openHour": 11,
                    "openMinute": 30,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [],
            "is24Hours": false,
        }, {
            "storeId": "77788899",
            "name": "Coastline Grill",
            "category": ["happy_hour", "deals_and_discounts", "special_events"],
            "cuisineTypes": ["Seafood", "American", "Grill", "Bar"],
            "contactNumber": "6046330175",
            "location": {
                "latitude": 49.3023,
                "longitude": -123.0925,
            },
            "ratings": [1.0, 3.5, 4.5, 5.0, 4.0, 4.0, 5.0, 3.0, 4.5, 4.5, 3.5, 4.0, 4.5, 5.0, 3.0, 4.5, 5.0, 4.5, 3.5, 4.0],
            "totalRatings": 199,
            "menus": [
                {
                    "itemId": "12345678",
                    "name": "Grilled Salmon",
                    "price": 24.99,
                    "type": "food",
                },
                {
                    "itemId": "12345679",
                    "name": "Lobster Roll",
                    "price": 28.99,
                    "type": "food",
                },
                {
                    "itemId": "12345680",
                    "name": "Clam Chowder",
                    "price": 10.99,
                    "type": "food",
                },
                {
                    "itemId": "12345681",
                    "name": "House-made Lemonade",
                    "price": 4.99,
                    "type": "drink",
                },
                {
                    "itemId": "12345682",
                    "name": "Craft Beer",
                    "price": 7.99,
                    "type": "alcohol",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 16,
                    "startMinute": 0,
                    "endHour": 19,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
            ],
            "is24Hours": false,
        }, {
            "storeId": "55566677",
            "name": "North Shore Cafe",
            "category": ["happy_hour", "all_you_can_eat"],
            "cuisineTypes": ["Cafe", "Canadian", "Breakfast", "Brunch"],
            "contactNumber": "6047693131",
            "location": {
                "latitude": 49.3441,
                "longitude": -123.0158,
            },
            "ratings": [2.5, 4.0, 4.5, 4.5, 3.0, 3.5, 5.0, 4.0, 4.5, 3.5, 3.0, 5.0, 4.0, 4.5, 4.0, 4.5, 3.5, 4.0, 5.0, 3.0],
            "totalRatings": 121,
            "menus": [
                {
                    "itemId": "98765432",
                    "name": "Avocado Toast",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "98765433",
                    "name": "Pancake Stack",
                    "price": 9.99,
                    "type": "food",
                },
                {
                    "itemId": "98765434",
                    "name": "Egg Benedict",
                    "price": 13.99,
                    "type": "food",
                },
                {
                    "itemId": "98765435",
                    "name": "Cappuccino",
                    "price": 4.49,
                    "type": "drink",
                },
                {
                    "itemId": "98765436",
                    "name": "Smoothie",
                    "price": 5.99,
                    "type": "drink",
                },
                {
                    "itemId": "98765437",
                    "name": "Mimosa",
                    "price": 6.99,
                    "type": "alcohol",
                },
            ],
            "businessHours": [
                {
                    "openHour": 7,
                    "openMinute": 30,
                    "closeHour": 15,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 8,
                    "openMinute": 0,
                    "closeHour": 14,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 14,
                    "startMinute": 0,
                    "endHour": 17,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
            ],
            "is24Hours": false,
        }, {
            "storeId": "12345678",
            "name": "Vancouver Grill",
            "category": ["special_events", "deals_and_discounts"],
            "cuisineTypes": ["Steakhouse", "American", "BBQ"],
            "contactNumber": "6040175889",
            "location": {
                "latitude": 49.2827,
                "longitude": -123.1216,
            },
            "ratings": [3.0, 4.0, 4.5, 4.0, 5.0, 3.5, 3.0, 4.5, 4.0, 4.0, 3.5, 4.5, 5.0, 4.0, 3.5, 4.0, 3.0, 4.5, 5.0, 4.0],
            "totalRatings": 572,
            "menus": [
                {
                    "itemId": "12345679",
                    "name": "Ribeye Steak",
                    "price": 24.99,
                    "type": "food",
                },
                {
                    "itemId": "12345680",
                    "name": "BBQ Ribs",
                    "price": 22.99,
                    "type": "food",
                },
                {
                    "itemId": "12345681",
                    "name": "Grilled Salmon",
                    "price": 21.99,
                    "type": "food",
                },
                {
                    "itemId": "12345682",
                    "name": "Classic Margarita",
                    "price": 7.99,
                    "type": "alcohol",
                },
                {
                    "itemId": "12345683",
                    "name": "Whiskey Sour",
                    "price": 8.99,
                    "type": "alcohol",
                },
            ],
            "businessHours": [
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 17,
                    "openMinute": 0,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [],
            "is24Hours": false,
        }, {
            "storeId": "23456789",
            "name": "Sunset Cafe",
            "category": ["special_events", "all_you_can_eat"],
            "cuisineTypes": ["Cafe", "Brunch", "Bakery"],
            "contactNumber": "6044218175",
            "location": {
                "latitude": 49.2606,
                "longitude": -123.1149,
            },
            "ratings": [4.5, 4.0, 3.5, 5.0, 4.0],
            "totalRatings": 5,
            "menus": [
                {
                    "itemId": "23456790",
                    "name": "Eggs Benedict",
                    "price": 12.99,
                    "type": "food",
                },
                {
                    "itemId": "23456791",
                    "name": "Avocado Toast",
                    "price": 9.99,
                    "type": "food",
                },
                {
                    "itemId": "23456792",
                    "name": "Cappuccino",
                    "price": 4.50,
                    "type": "drink",
                },
                {
                    "itemId": "23456793",
                    "name": "Mimosas",
                    "price": 7.50,
                    "type": "alcohol",
                },
                {
                    "itemId": "23456794",
                    "name": "Croissants",
                    "price": 3.99,
                    "type": "food",
                },
            ],
            "businessHours": [
                {
                    "openHour": 8,
                    "openMinute": 0,
                    "closeHour": 15,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 9,
                    "openMinute": 0,
                    "closeHour": 16,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [],
            "is24Hours": false,
        }, {
            "storeId": "34567890",
            "name": "The Green Garden",
            "category": ["happy_hour", "special_events"],
            "cuisineTypes": ["Vegetarian", "Vegan", "Healthy", "Cafe"],
            "contactNumber": "6040682614",
            "location": {
                "latitude": 49.2580,
                "longitude": -123.1143,
            },
            "ratings": [5.0, 4.5, 4.0, 4.0, 3.5, 4.5, 5.0],
            "totalRatings": 7,
            "menus": [
                {
                    "itemId": "34567891",
                    "name": "Vegan Burger",
                    "price": 14.99,
                    "type": "food",
                },
                {
                    "itemId": "34567892",
                    "name": "Green Smoothie",
                    "price": 6.50,
                    "type": "drink",
                },
                {
                    "itemId": "34567893",
                    "name": "Tofu Stir Fry",
                    "price": 13.99,
                    "type": "food",
                },
                {
                    "itemId": "34567894",
                    "name": "Quinoa Salad",
                    "price": 11.99,
                    "type": "food",
                },
                {
                    "itemId": "34567895",
                    "name": "Cold Brew Coffee",
                    "price": 5.99,
                    "type": "drink",
                },
            ],
            "businessHours": [
                {
                    "openHour": 8,
                    "openMinute": 0,
                    "closeHour": 18,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 10,
                    "openMinute": 0,
                    "closeHour": 16,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [
                {
                    "startHour": 16,
                    "startMinute": 0,
                    "endHour": 18,
                    "endMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
            ],
            "is24Hours": false,
        }, {
            "storeId": "12345678",
            "name": "Super bbq",
            "category": ["all_you_can_eat", "special_events"],
            "cuisineTypes": ["American", "Grill", "BBQ", "Steakhouse"],
            "contactNumber": "6040689972",
            "location": {
                "latitude": 49.2827,
                "longitude": -123.1207,
            },
            "ratings": [5.0, 4.5, 4.5, 4.0, 5.0, 4.0, 4.5, 4.0],
            "totalRatings": 8,
            "menus": [
                {
                    "itemId": "12345679",
                    "name": "BBQ Ribs",
                    "price": 22.99,
                    "type": "food",
                },
                {
                    "itemId": "12345680",
                    "name": "Steak and Fries",
                    "price": 19.99,
                    "type": "food",
                },
                {
                    "itemId": "12345681",
                    "name": "Grilled Salmon",
                    "price": 24.99,
                    "type": "food",
                },
                {
                    "itemId": "12345682",
                    "name": "Caesar Salad",
                    "price": 9.99,
                    "type": "food",
                },
                {
                    "itemId": "12345683",
                    "name": "Iced Tea",
                    "price": 3.50,
                    "type": "drink",
                },
            ],
            "businessHours": [
                {
                    "openHour": 11,
                    "openMinute": 0,
                    "closeHour": 22,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["MON", "TUE", "WED", "THU", "FRI"],
                },
                {
                    "openHour": 12,
                    "openMinute": 0,
                    "closeHour": 23,
                    "closeMinute": 0,
                    "isNextDay": false,
                    "daysOfWeek": ["SAT", "SUN"],
                },
            ],
            "happyHours": [],
            "is24Hours": false,
        },
    ],
};
//# sourceMappingURL=stores-data.js.map